### ISSUE TITLE
Warning: Character length of actual argument shorter than of dummy argument 'nom_param'

### ISSUE THREAD

**Issue by lucasbarbedo83** [CNES/RadiativeTransferCode-OSOAA#11]
I have these warming messages from GFORTRAN:
How compile correctly without these warmings?

------------> Compilation of /home/lxbarbedo/RadiativeTransferCode-OSOAA-master/obj/OSOAA_MAIN.o
/home/lxbarbedo/RadiativeTransferCode-OSOAA-master/src/OSOAA_MAIN.F:4356.51:

         CALL OSOAA_COMPA_SIMU_VALUE(WA_SIMU,"DBL",'-OSOAA.Wa:',
                                                   1
Warning: Character length of actual argument shorter than of dummy argument 'nom_param' (10/450) at (1)
/home/lxbarbedo/RadiativeTransferCode-OSOAA-master/src/OSOAA_MAIN.F:4362.19:

     &             '-ANG.Rad.NbGauss:',11,TRACE,CAS_REPRISE,IER)
                   1
Warning: Character length of actual argument shorter than of dummy argument 'nom_param' (17/450) at (1)
/home/lxbarbedo/RadiativeTransferCode-OSOAA-master/src/OSOAA_MAIN.F:4367.35:

     &          FICANGLES_USER_LUM,'-ANG.Rad.UserAngFile:',  
                                   1
Warning: Character length of actual argument shorter than of dummy argument 'nom_param' (21/450) at (1)
/home/lxbarbedo/RadiativeTransferCode-OSOAA-master/src/OSOAA_MAIN.F:4372.49:

         CALL OSOAA_COMPA_SIMU_VALUE(TETAS,"DBL",'-ANG.Thetas:',
                                                 ...

**Comment by blafranc** [comment]
Dear user,

Thank you for your interest in using the OSOAA radiative transfer code.

The occurence of "warning" messages during the compilation step of OSOAA is expected because it highly depends on a given compiler. The warning messages are thus not an issue as far as the overall OSOAA compilation is fine (i.e., no compilation errors). The OSOAA model will then run correctly. 

If you want to hide the warning messages, you can add the option **-w** in the compilation makefile:
* edit the file **gen/Makefile_OSOAA.gfortran** (or .f77 or g77 depending on your compiler). 
* in line 48, changes : "CCOPTS  =  -O"  to "**CCOPTS  =  -O  -w**" 
* save the file and try the compilation again.

I hope this answer helps you.

Best regards

**Comment by lucasbarbedo83** [comment]
Yes, it solves the problem. 
I appreciate your support.
A+ Lucas
