### ISSUE TITLE
Mueller Matrix vs. Legendre

### ISSUE THREAD

**Issue by lucasbarbedo83** [CNES/RadiativeTransferCode-OSOAA#13]
OSOAA calculates Legendre from Mueller Matrix.
How can I have the inverse calculation: Mueller Matrix from Legendre (i.e., alpha, beta, gamma,Zeta)
In other words: PM_PHYTO.TXT to HYD_MOD.TXT.

See a example of PM_PHYTO.TXT
RADIATIVE PROPERTIES OF PARTICLES
---------------------------------
EXTINCTION CROSS SECTION (mic^2)     :  0.69804E+01
SCATTERING CROSS SECTION (mic^2)     :  0.49895E+01
ASYMMETRY FACTOR (no truncation)     :  0.99798E+00
MEAN PARTICULES ALTITUDE/DEPTH (m)   :  -999.000
VOLUME OF A MEAN PARTICULE (mic^3)   : -0.99900E+03
MEAN REFRACTIVE INDEX (real part)    : -999.0000
TRUNCATION COEFFICIENT               :  1.97529
SINGLE SCATTERING ALBEDO (truncation):  0.03004
---------------------------------
PHASE MATRIX COEFFICIENTS FOR K=0 TO  80
ALPHA(K)        BETA11(K)       GAMMA12(K)      ZETA(K)
 0.00000000E+00  0.10000000E+01  0.00000000E+00  0.00000000E+00
 0.00000000E+00  0.25090898E+01  0.00000000E+00  0.00000000E+00
 0.43286400E+01  0.34467669E+01 -0.24962208E+00  0.41430265E+01

**Comment by blafranc** [comment]
Dear Lucas,

I understand you want to get the phase functions defined in the Mueller matrix (as a function of the scattering angle), rather than the Greek coefficients of their expansions in Legendre functions.

The phase functions are available in the logfiles.
**Use the keyword -HYD.Log** to get the logfile associated to the calculation of the optical properties of hydrosols (it will be created in the Advanced_Output repository). 
Track "HYDROSOL COMPUTATIONS: RESULTS" in the file to find the section with this data.

Bruno

**Comment by lucasbarbedo83** [comment]
Yes! I found it. Perfect.
Thank you!
